name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Validate JSON structure
      run: |
        echo "🔍 Validating JSON syntax..."
        python -m json.tool lngal_data.json > /dev/null
        echo "✅ JSON syntax is valid"
        
        echo "🔍 Checking required fields..."
        # Basic validation that categories exist
        if ! grep -q '"categories"' lngal_data.json; then
          echo "❌ Missing 'categories' field in JSON"
          exit 1
        fi
        
        # Check that there's at least one category
        category_count=$(python -c "import json; data=json.load(open('lngal_data.json')); print(len(data.get('categories', [])))")
        if [ "$category_count" -eq 0 ]; then
          echo "❌ No categories found in JSON"
          exit 1
        fi
        
        echo "✅ Found $category_count categories"
        echo "✅ JSON structure validation passed"
    
    - name: Test HTML validity
      run: |
        echo "🔍 Checking HTML structure..."
        # Basic HTML validation
        if ! grep -q '<html' index.html; then
          echo "❌ Invalid HTML structure"
          exit 1
        fi
        
        if ! grep -q '</html>' index.html; then
          echo "❌ HTML not properly closed"
          exit 1
        fi
        
        echo "✅ HTML structure is valid"
    
    - name: Check required files
      run: |
        echo "🔍 Checking required files exist..."
        required_files=("index.html" "css/styles.css" "js/app.js" "js/components.js" "lngal_data.json")
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Required file missing: $file"
            exit 1
          fi
          echo "✅ Found: $file"
        done
        
        echo "✅ All required files present"
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: '.github,plan.md'
        
    - name: Deployment summary
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "📊 Site will be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
        echo "⏱️ Changes may take a few minutes to appear"